env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=b97608ade94720b1d516dd787aea844c0cc2c4338aecfee997896d739ca5db48

dist: xenial
language: go
go:
  - 1.11.x
  - tip
install: go mod vendor
script:
  - ./build-test-fixtures.sh
  - go test -mod vendor -coverprofile=c.out -covermode=atomic

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
